install:
  - "SET PATH=C:\\Python35;C:\\Python35\\Scripts;C:\\Program Files\\PostgreSQL\\9.4\\bin;%PATH%"
  - "pip install -r requirements.txt"
  - "pip install coverage"

build: off

test_script: coverage run manage.py test

after_test:
  - pip install codecov
  - codecov
